### ISSUE TITLE
[1pt] All Item class properties (Group Task)

### ISSUE THREAD

**Issue by ookino** [xtrahuman/catalog#6]
All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.

**Comment by yaseerokino** [comment]
Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
